### ISSUE TITLE
anomalia e ricerca in elenco movimenti gestione cassa

### ISSUE THREAD

**Issue by monicapgiare** [iGruppi/iGruppi#123]
Nell'elenco dei movimenti della Gestione Cassa http://live.igruppi.com/gestione-cassa/index/page/0
ho notato alcune cose:
- a volte l'ultimo movimento che appare in una pagina, viene ripetuto in quella successiva (vedi movimento evidenziato)

![movimenti cassa 3](https://cloud.githubusercontent.com/assets/11527743/19512186/03ec93ea-95eb-11e6-8606-abbad6a13858.jpg)

![movimenti cassa 4](https://cloud.githubusercontent.com/assets/11527743/19512187/03ecb79e-95eb-11e6-9ff6-d62fef981583.jpg)

Questo rende difficile effettuare dei controlli. Per esempio, senza guardare il #id, sembra che la stessa operazione sia stata inserita doppia.
- a volte i movimenti non appaiono in ordine di #id (vedi movimenti segnati in rosso nell'immagine sopra)
- l'ordine dei movimenti cambia, anche dopo mezz'ora o forse ogni volta che si esce e rientra? Per esempio, dopo un po' l'operazione che si ripeteva su due pagine, di cui ho messo la schermata sopra, non era più ripetuta e la stessa pagina appariva diversamente, senza che siano stati inseriti nuovi movimenti.

![movimenti cassa 5](https://cloud.githubusercontent.com/assets/11527743/19513131/2dcf04f0-95ef-11e6-93c1-2555a08f2fa7.jpg)

A occhio mi sembra che comunque i movimenti appaiano in ordine di data.

L'ordine dei movimenti sarebbe poco importante se ci fosse uno strumento di ricerca (per nome utente, data, id ordine, importo). 
Quando ci sono tante pagine e tante operazioni, è difficile, per esempio, verificare di aver registrato un bonifico o una quota associativa.

**Comment by StefanoMenozzi** [comment]
Il problema dovrebbe essere stato risolto poichè è stata inserita ai fini dell'ordinamento una nuova chiave aggiuntiva (oltre alla data decrescente, è stato aggiunto l'id movimento decrescente); riverificare che tutto funzioni ma dovrebbe il problema dovrebbe essere risolto. Si potrebbe pensare di aggiungere la funzionalità di ricerca o di filtrazione in base a diversi campi/criteri.
