### ISSUE TITLE
Nel riepilogo generale di un ordine deve essere aggiunta alla Quota Ord. la sua unità di misura 

### ISSUE THREAD

**Issue by StefanoMenozzi** [iGruppi/iGruppi#125]
Nel riepilogo generale dell'ordine deve essere aggiunta l'unità di misura a fianco della colonna per evitare errori grossolani. 
E' riportata infatti l'unità di misura ma questa si riferisce solo al costo ed alla Quota Reale, non alla quota Ordinata.
Se ad esempio ho una latta d'olio da 5 litri ed ho inserito il costo al litro, l'unità di misura è litro,  Perciò è corretto che mi sia presentato Q.ta reale 5 , Prezzo 10€ e u.d.m "Litro". Ma litro non vale per la Quota ord. che dovrebbe avere a fianco invece l'ud.m sua ovvero "confezione".
Sarebbe ancora meglio che ogni grandezza fisica avesse la sua unità di misura a fianco per maggior chiarezza. Tipo nell'ordine Quota reale, "confezione", Quota ordinata ,"litri" , Prezzo , "€/litro"

**Comment by monicapgiare** [comment]
Sono d'accordo!
Forse questa segnalazione si riferisce al Riepilogo "totale ordinato". Io mi trovo ogni tanto in difficoltà nel Riepilogo "Parziali per utente" per lo stesso motivo.

Per esempio, io ho ordinato 2 tortelli. Guardando il mio ordine personale dalla homepage, vedo appunto 2 e, guardando la pezzatura, capisco che è 1 kg.

![schermata 2016-11-16 alle 15 38 57](https://cloud.githubusercontent.com/assets/11527743/20351367/d8600e94-ac12-11e6-96ec-c79ee8658a4a.png)

Mentre nel riepilogo dell'ordine, utilizzato soprattutto da chi deve distribuire, vedo 1 kg e devo pensarci un po' per capire che significa 1 kg non 1 "porzione". Dipende quale si guarda per primo e a quale scopo ...

![quantita](https://cloud.githubusercontent.com/assets/11527743/20351299/8c6f64a8-ac12-11e6-829b-7cd79213c411.png)

Penso che l'argomento sia lo stesso. Cioè tutto sarebbe più chiaro se per ogni quantità ci fosse la sua u.d.m.
Se non è lo stesso argomento, scusate e, chi è in grado, può dividere l'issue in due.

**Comment by StefanoMenozzi** [comment]
L'argomento è il medesimo

**Comment by StefanoMenozzi** [comment]
Aggiornato da Davide; quindi : videata riepilogo ordine nelle diverse situazioni modificata con le diverse unità di misura per le quantità ordinate, quantità reale, prezzo. Così dovrebbe essere risolto su tutte le situazioni. Se per caso vedi situazioni non risolte riapriamo l'Issue. Mi sembra che graficamente oltre che come logica sia molto più leggibile e chiaro.
