### ISSUE TITLE
Metodo di ripartizione delle spese  / costi dell'ordine

### ISSUE THREAD

**Issue by StefanoMenozzi** [iGruppi/iGruppi#13]
Vedo che ora il metodo di ripartizione delle spese è a testa.
E' possibile inserire la modalità di scelta?

Procedura di ripartizione delle spese di spedizione:
 * per testa
 * in percentuale

**Comment by Jazzo** [comment]
Per ora ho implementato questi 3 metodi:
* Ripartita per utente, l'importo viene ripartito in parti uguali sugli utenti
* Ripartita per utente in % sul totale ordinato da ogni singolo utente
* Fissa per utente, importo fisso per ogni utente

**Comment by monicapgiare** [comment]
Ho visto che inserendo l'importo con il punto che separa i decimali, va tutto bene. Inserendo l'importo con la virgola, i decimali vengono ignorati. Cioè se inserisco 3,40 considera solo 3 euro. Ho provato su Beta ma immagino che sia la stessa cosa su Live perchè in un ordine è stata inserita una spesa extra di 0,79 euro ma non è stato aggiunto nulla.
Inoltre ho visto che è possibile inserire e ripartire un importo negativo. Potrebbe essere utile in caso di uno sconto extra?
