### ISSUE TITLE
Installare Igruppi

### ISSUE THREAD

**Issue by markust4w** [iGruppi/iGruppi#136]
Buongiorno,

Allo stesso modo sapete indicarmi come popolare il database dopo averlo creato con l'sql igruppi2_create?

I form per l'iscrizione non vengono caricati, ricarica la homepage...

Avete un manuale di installazione?

Grazie

**Comment by Jazzo** [comment]
@markust4w
In [questo issue](https://github.com/iGruppi/iGruppi/issues/1) trovi diverse risposte a problemi durante il processo di installazione. Altre info sull'installazione DB sono nella [home del progetto qui su github](https://github.com/iGruppi/iGruppi).

**Comment by markust4w** [comment]
Grazie, sono riuscito ad installare il db, e ad inserire i primi campi. Ho un problema con la home cliccando su login o register ricarica sempre la home, non si accede alle relative pagine. Ho attivato il tutto su un dominio di terzo livello. Non ho trovato nulla nei commenti precedenti...

**Comment by Jazzo** [comment]
@markust4w 
non sta funzionando il file .htaccess che utilizza il mod_rewrite per il parsing dell'url:
https://github.com/iGruppi/iGruppi/issues/63

**Comment by markust4w** [comment]
Immaginavo, avevo visto quel commento sul server apache, ma non posso accedere al virtual host sul server. Cosa posso fare? Ho provato a disabilitare htaccess ma non funziona. Oppure spostare e variare l'htaccess?
