### ISSUE TITLE
ORDINE: Manca pulsante SALVA (solo su Tablet)

### ISSUE THREAD

**Issue by claudiogiare** [iGruppi/iGruppi#14]
Provato sia su IPAD che su Android. Sembra non ci sia il pulsante Salva quando si compila un ordine,   se si accede a Igruppi via tablet.

**Comment by Jazzo** [comment]
Mi dai qualche dato in più sul tuo tablet?
Perchè io col mio (Samsung Galaxy Tab4) lo vedo senza problemi. Con smartphone no ma per questa risoluzione pensavo di lavorarci alla 2.1

**Comment by claudiogiare** [comment]
ipad 2 Safari.
Il 22/ago/2015 16:43 "Davide Gullo" <notifications@github.com> ha scritto:

Mi dai qualche dato in più sul tuo tablet?
Perchè io col mio (Samsung Galaxy Tab4) lo vedo senza problemi. Con
smartphone no ma per questa risoluzione pensavo di lavorarci alla 2.1

—
Reply to this email directly or view it on GitHub
<https://github.com/iGruppi/iGruppi/issues/14#issuecomment-133711241>.
