### ISSUE TITLE
Bug: apertura ordine error

### ISSUE THREAD

**Issue by markust4w** [iGruppi/iGruppi#141]
Buongiorno,

mi trovo errore nell'apertura di un ordine tramite un referente, inoltre ad ogni operazione mi trovo uno warning, aggiungo che le email non pervengono ed in abilitazione di un utente rimane in un download perenne (nonostante l'utente venga subito attivato ma la email non perviene):

Warning:
Warning: PDOStatement::execute(): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'og.archiviato' in 'field list' in /........./resources/Model/Db/Ordini.php on line 25

Errore:
Se il referente apre l'ordine impostando una data ecco cosa accade:
Fatal error: Call to a member function getIdOrdine() on null in /....../resources/Controller/GestioneOrdini.php on line 234

Attendo info quanto prima

Grazie

**Comment by Jazzo** [comment]
Le email non partono perchè non è configurato correttamente l'ambiente. Per questo il "download perenne".
Per quanto riguarda il warning sul campo **archiviato** della tabella ordini con tutta probabilità hai usato un dump del DB diverso dalla versione del codice che stai utilizzando.
[Vedi documentazione sul DB.](https://github.com/iGruppi/iGruppi/wiki/01.-Struttura-database)

**Comment by markust4w** [comment]
Grazie Davide, ora guardo per la versione installata ed il DB.

Dove posso verificare la funzionalità delle email? Quali file devo
controllare, ho trovato un file mail in cui erano inseriti tuoi dati
email...

Il giorno sab 8 lug 2017 alle 15:40 Davide Gullo <notifications@github.com>
ha scritto:
