### ISSUE TITLE
Bug email remember password

### ISSUE THREAD

**Issue by markust4w** [iGruppi/iGruppi#142]
Ho un bug nella versione production live. In generale le email non vengono inviate. In particolare se richiedo la password:
rning: fopen(......../tmp/LOG_EMAIL_SENT_12072017.html): failed to open stream: No such file or directory in ......../library/MyFw/Mail.php on line 80

Warning: fwrite() expects parameter 1 to be resource, boolean given in ........./library/MyFw/Mail.php on line 81

Warning: fclose() expects parameter 1 to be resource, boolean given in ........../library/MyFw/Mail.php on line 82

**Comment by Jazzo** [comment]
@markust4w scusami ma **potresti evitare di "classificare" tutto come bug visto che nel 99% dei casi si tratta di scarsa conoscenza del sistema?** Grazie.

Anche in questo caso infatti è un problema di configurazione, se dai un'occhiata al codice capisci che il sistema sta lavorando in **development** e non in production.

**Comment by markust4w** [comment]
..ok, a questo punto ti chiedo quale versione utlizzare... quali database
utilizzare ed in caso quale codice devo utilizzare per utilizzare il
sistema in production. Il software è stato installato su un server online
rispondente ad un dominio di terzo livello. Mi fai sapere se mi puoi
fornire queste informazioni? Grazie




Il giorno 13 luglio 2017 18:31, Davide Gullo <notifications@github.com> ha
scritto:
