### ISSUE TITLE
problema installazione

### ISSUE THREAD

**Issue by MrWolf76** [iGruppi/iGruppi#2]
Ciao Davide complimenti per il tuo lavoro... se fa ciò che promette, è uno dei migliori sw sui generis in circolazione!!
Ho provato ad installare il sw su un server classico aruba, ho scaricato lo zip ed i codici da inserire nella dir library, il dump di mysql ed ho messo tutto su...
appena lancio mi da questo errore:
Class 'Zend_Exception' not found in /web/htdocs/www.miosito.it/home/iGruppi/library/MyFw/Autoloader.php on line 16
mi puoi aiutare?
Grazie

**Comment by Jazzo** [comment]
Vedi installazione ambiente di sviluppo via Vagrant:
https://github.com/iGruppi/Vagrant-Dev-Env
