### ISSUE TITLE
Anagrafica Utenti

### ISSUE THREAD

**Issue by claudiogiare** [iGruppi/iGruppi#25]
Prevederei l'aggiunta di campi anagrafici che riportano informazioni importi per la gestione operativa di un GAS.
In particolare:
-Contatto telefonico
-Indirizzo (in futuro mappa) utile per le consegne/ritiri
-Flag Gasista in Prova (per adesso solo informativo)
-Note (info utili per l'operatività del GAS: es. lavoro in zona Baragalla, vado in palaestra al martedi in quella zona, ecc.)

Queste informazioni (FACOLTATIVE) dovranno essere aggiornabili dall'utente stesso e saranno consultabili da tutti i membri del gruppo di appartenenza

**Comment by claudiogiare** [comment]
In futuro si potrà scaricare la vCard di ogni utente appartenente al proprio gruppo direttamente da iGruppi nei contatti del proprio smartphone

**Comment by claudiogiare** [comment]
Sarebbe bene anche visualizzare l'anteprima dei ruoli coperti dai vari utenti (es. CONTABILE, REFERENTE di QUESTO, REFERENTE DI QUELLO) senza dover entrare nei singoli utenti!

**Comment by claudiogiare** [comment]
Inoltre la lista degli utenti è ordinata per cognome, ma viene visualizzato prima il nome. Sarebbe meglio vedere prima il cognome.
![schermata 07-2457220 alle 23 03 47](https://cloud.githubusercontent.com/assets/7717889/8735093/8f8275f2-2c0e-11e5-8793-0ec7686c5d65.png)

**Comment by claudiogiare** [comment]
In futuro dovremo/potremo rendere configurabile l'indirizzo mail al quale vengono inviate le notifiche, dando anche la possibilità di aggiungere più mail. Basta un campo da compilare per ogni utente dove inserire tutti gli indirizzi mail che devono essere raggiunti dalle notifiche (separati da virgola o punto e virgola)

**Comment by Jazzo** [comment]
Il campo è già configurabile, cliccando su Modifica.
Inoltre col punto e virgola dovrebbe anche funzionare ma ora verifico.

**Comment by Jazzo** [comment]
Ok, ho aggiunto i campi mancanti in Modifica. Visualizzazione in elenco con anche etichette per Amministratore, Contabile, In prova e Disabilitato. Vedi screenshot:

![schermata 2015-09-16 alle 22 51 32](https://cloud.githubusercontent.com/assets/1465434/9930948/9691cd66-5d37-11e5-96a9-e431bfda7cde.png)

**Comment by claudiogiare** [comment]
WONDERFUL!
Il 17/set/2015 12:29, "Davide Gullo" <notifications@github.com> ha scritto:
