### ISSUE TITLE
Menu a tendina non visualizzati correttamente

### ISSUE THREAD

**Issue by claudiogiare** [iGruppi/iGruppi#27]
Come mai i menu a tendina si vedono "tagliati"?
MI succede con tutti i browser (ie, firefox, chrome)

**Comment by Jazzo** [comment]
Allega screenshot, thanks! ;-)

2015-03-24 15:57 GMT+01:00 claudiogiare <notifications@github.com>:

> Come mai i menu a tendina si vedono "tagliati"?
> MI succede con tutti i browser (ie, firefox, chrome)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Jazzo/iGruppi/issues/27>.
>



-- 
Davide Gullo, Consulente Web (professionista disciplinato ai sensi della
legge 4/2013)
http://www.m4ss.net
gullo@m4ss.net

**Comment by claudiogiare** [comment]
![menutendina](https://cloud.githubusercontent.com/assets/7717889/6805041/41c08baa-d241-11e4-803e-d36e2c255051.jpg)

**Comment by Jazzo** [comment]
PC? Windows 7?

2015-03-24 16:17 GMT+01:00 claudiogiare <notifications@github.com>:

> [image: menutendina]
> <https://cloud.githubusercontent.com/assets/7717889/6805041/41c08baa-d241-11e4-803e-d36e2c255051.jpg>
>
>
>

**Comment by claudiogiare** [comment]
Win 8.1
