### ISSUE TITLE
Il REFERENTE PRODUTTORE INTERNO non riesce ad aprire ordini

### ISSUE THREAD

**Issue by claudiogiare** [iGruppi/iGruppi#30]
![problema_referente](https://cloud.githubusercontent.com/assets/7717889/6880389/6eaa0632-d52f-11e4-8004-9741d017090e.jpg)
Ho impostato l'utente Diego Marchi come referente interno del Pettirosso, ma entrando col suo utente non riesco ad aprire ordini per il gruppo per quel produttore.

**Comment by Jazzo** [comment]
L'ordine si apre dall'area "Gestione Ordini" tramite apposito pulsante "Nuovo Ordine".

![schermata 2015-03-28 alle 23 05 49](https://cloud.githubusercontent.com/assets/1465434/6883119/28c29f7e-d59f-11e4-9b70-8f45e28276c3.png)
