### ISSUE TITLE
Problema su SALVA ORDINE

### ISSUE THREAD

**Issue by claudiogiare** [iGruppi/iGruppi#31]
Non riesco a SALVARE UN ORDINE.
Appena clicco sul pulsante verde mi dà un errore SQL e non salva le qtà ordinate.
Warning: PDOStatement::execute(): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`cligrupp_ig_beta2`.`ordini_user_prodotti`, CONSTRAINT `fk_ordini_user_prodotti_ordini_user1` FOREIGN KEY (`iduser`, `idordine`) REFERENCES `ordini_users` (`iduser`, `idordine`) ON DELETE NO A) in /home2/cligrupp/igruppi/beta2/resources/Model/Db/Ordini.php on line 202

![problema_salvaordine](https://cloud.githubusercontent.com/assets/7717889/6880432/d13542de-d530-11e4-875f-d6dc4bba6922.jpg)

**Comment by Jazzo** [comment]
Ho aggiunto anche il Salvataggio automatico, nel senso che ho eliminato il pulsante verde SALVA ORDINE, ora basta il click sul + o -.
Quel testo "salvataggio automatico" può creare confusione?
