### ISSUE TITLE
Apertura Nuovo Ordine

### ISSUE THREAD

**Issue by Jazzo** [iGruppi/iGruppi#32]
Ho notato che qualsiasi utente può aprire un ordine andando in Gestione ordini e +Nuovo ordine, anche per nessun produttore/listino, soltanto inserendo le date.
Non so a chi possa venire in mente di farlo però è possibile.
(Monica)

**Comment by Jazzo** [comment]
E' un bug. Se un utente non è referente di nessun Produttore non dovrebbe poter aprire Ordini.

**Comment by Jazzo** [comment]
Fixed. Ora un utente vede il pulsante solo se è Referente di almeno 1 produttore.

**Comment by monicapgiare** [comment]
Grazie! In effetti chi non è referente vede solo "filtra ordini" e va bene.
Chi è referente vede il pulsante Nuovo Ordine ma non può scegliere il listino.
Chi è gestore produttore vede sia il pulsante sia il menù a tendina dei listini.
E' corretto così o c'è ancora qualcosa da sistemare?

![utente non referente nuovo ordine](https://cloud.githubusercontent.com/assets/11527743/6897104/8d0cc182-d6f1-11e4-9267-69ec8771666b.png)
![superadmin correggio nuovo ordine](https://cloud.githubusercontent.com/assets/11527743/6897105/8f8dc2b2-d6f1-11e4-8554-abbc64542635.png)
![gestore produttore nuovo ordine](https://cloud.githubusercontent.com/assets/11527743/6897106/92a4c41e-d6f1-11e4-940a-d06a72663b02.png)

**Comment by Jazzo** [comment]
Per quanto riguarda il "Referente produttore" no, è da sistemare. Nel senso
che, pur essendo referente, se non ha Listini disponibili (o perchè non ne
ha creati o perchè non ce ne sono di condivisi per lui/lei) non deve poter
creare un Ordine.

Per il "Gestore produttore" invece non credo che veda il pulsante a meno
che questo non sia anche Referente produttore. Il caso che mi riporti in
esempio di "Silvia Rondini" è così?

**Comment by monicapgiare** [comment]
Sì, Silvia Rondini è sia gestore che referente interno

**Comment by Jazzo** [comment]
Ok, ora se non ci sono Listini disponibili per apire un nuovo Ordine appare questo messaggio:

![schermata 2015-04-07 alle 17 50 48](https://cloud.githubusercontent.com/assets/1465434/7027292/05b410e6-dd4f-11e4-87c7-ee54ba3af715.png)

Fatemi sapere se può andar bene come messaggio/soluzione.
