### ISSUE TITLE
GESTIONE LISTINI

### ISSUE THREAD

**Issue by monicapgiare** [iGruppi/iGruppi#33]
http://beta2.igruppi.com/listini/view/idlistino/2

![elenco listini](https://cloud.githubusercontent.com/assets/11527743/6900154/e9a3d8dc-d704-11e4-8c66-cdfad4b032d2.png)

cliccando su "visualizza listino", si vede solo questo:

![visualizza listino](https://cloud.githubusercontent.com/assets/11527743/6900159/ebfa2c6c-d704-11e4-8717-55d0b7d651b4.png)

questo utente non è nè gestore produttore nè referente interno per questi listini. Va bene così?

**Comment by Jazzo** [comment]
Direi di si. Tutti gli utenti possono vedere i listini disponibili per il proprio GAS.
In Produttori invece si visualizza l'Anagrafica prodotti, cosa diversa dai Listini.
Per me è ok. Vi torna?

**Comment by monicapgiare** [comment]
Ok, per oggi è meglio che smetta!
Non ho usato il termine giusto e non ho scritto bene la domanda.
Cliccando su "visualizza listino" non si vede il listino ma appare la seconda immagine. Cioè appare Telefono: Email:

In questa frase "I listini sono però visualizzabili normalmente dall'elenco produttori > visualizza anagrafica prodotti per tutti gli utenti" con listini intendevo i prezzi - cosa diversa come dice Davide.

**Comment by StefanoMenozzi** [comment]
Entrando però nei Listini mi genera sempre 
il seguente messaggio di errore:

Siamo spiacenti, si è verificato un errore...
Errore 404: Pagina non trovata!

La pagina richiesta non è disponibile.

**Comment by monicapgiare** [comment]
http://beta2.igruppi.com/listini/edit/idlistino/4

Ho creato un listino privato impostato come non visibile:

![image](https://cloud.githubusercontent.com/assets/11527743/7671750/a701291a-fcdb-11e4-9d0b-e10f2f0b55b0.png)

Sia un socio qualsiasi che l'amministratore/fondatore, vedono ugualmente il listino nell'elenco, ma cliccando su "visualizza listino", appare l'errore che ha scritto Stefano. Quindi il listino si vede ma non si vede! Forse sarebbe meglio che i listini "non visibili" non apparissero neppure nell'elenco e che fossero visibili solo per il referente?

![image](https://cloud.githubusercontent.com/assets/11527743/7671768/1ebed9ac-fcdc-11e4-9171-3b092c12dbf1.png)

Inoltre, anche impostando il listino come privato visibile oppure condiviso visibile, entrando in "visualizza listino", appare lo stesso errore. In pratica l'unico che può vedere il dettaglio del listino è il referente.

**Comment by claudiogiare** [comment]
Confermiamo che i listini sono visibili a tutti gli utenti del gruppo.
Eliminiamo il filtro per tipologia listino (privato, condiviso, pubblico) ed inseriamo un'etichetta con questa informazione di fianco al titolo del listino stesso

**Comment by claudiogiare** [comment]
Altra segnalazione:
se il listino è impostato a VISIBILE = NO oppure c'è un periodo di validità già passato, il listino continua ad essere visibile a tutti gli utenti

**Comment by claudiogiare** [comment]
Non risulta possibile eliminare o rendere "non disponibili" prodotti da un listino già creato

**Comment by claudiogiare** [comment]
Al momento sembra possibile poter creare più listini con lo stesso nome. Questo può capitare per errore es. entrando ed uscendo dalla stessa maschera in 2 sessioni diverse

**Comment by claudiogiare** [comment]
Chiudo questo issue e lo scompongo in altri più specifici
