### ISSUE TITLE
ordine condiviso

### ISSUE THREAD

**Issue by monicapgiare** [iGruppi/iGruppi#35]
Saponaria:
Gestore Produttore nome15 (Iqbal) apre ordine e condivide con Giare Correggio + Camp9

Giare Camp9 ha impostato Alessandra Iori come referente interno.
Però inizialmente Alessandra Iori non può gestire l’ordine che appare con referente ordine: nessun referente ordine assegnato!
Gli utenti possono ordinare ugualmente (è ok?).

SuperAdmin Camp9 può gestire l’ordine e imposta Alessandra Iori come referente ordine
A questo punto Alessandra Iori può gestire l’ordine.

Giare Correggio ha impostato SuperAdmin come referente interno e Barbara Pergreffi come referente ordine.

TUTTI (nome15 + SuperAdmin Correggio + Barbara + Alessandra Iori) vedono lo stesso totale ordinato (dei 3 gas coinvolti?) e solo i nomi di chi ha ordinato nel proprio gruppo, gli altri ordini sono anonimi. Anche nella gestione cassa.

Nessuno tranne il Gestore Produttore nome15 (Iqbal) può modificare le date apertura e chiusura ordine.

Se si avanza l'ordine in Giare Correggio come arrivato, consegnato, ecc., risulta allo stesso stato anche in Giare Camp9 e Iqbal.

Non sono riuscita a modificare le quantità se, per esempio, un prodotto non arriva.

Se è tutto ok per un ordine condiviso, scusate e ignorate! 
Non avevo capito che funzionasse così ...

**Comment by claudiogiare** [comment]
Dico la mia (anche io per come l'ho capita):

MONICA: Giare Camp9 ha impostato Alessandra Iori come referente interno.
Però inizialmente Alessandra Iori non può gestire l’ordine che appare con referente ordine: nessun referente ordine assegnato!
Gli utenti possono ordinare ugualmente (è ok?).
CLAUDIO: Non è ok. L'ordine deve prima essere reso visibile dall'amministratore del Gruppo che assegna la gestione dell'ordine ad un INCARICATO (che potrebbe o no corrispondere col referente interno), Suggerisco che di default venga proposto il referente interno del produttore (o l'ultimo incaricato che ha gestito l'ordine?)

MONICA: TUTTI (nome15 + SuperAdmin Correggio + Barbara + Alessandra Iori) vedono lo stesso totale ordinato (dei 3 gas coinvolti?) e solo i nomi di chi ha ordinato nel proprio gruppo, gli altri ordini sono anonimi
CLAUDIO: solo il referente produttore che ha creato l'ordine (direi ch el'abbiamo ribattezzato SUPERVISORE ORDINE) potrà vedere l'ordine completo (di tutti i 3 gas coinvolti: importi e utenti che hanno ordinato), forse meglio in un'area apposita di "gestione dell'ordine condiviso".  (mi piace che gli utenti di altri gruppi siano anonimi per privacy , anche se potrebbe essere scomodo per capirsi in caso di domande sull'ordine. Pensiamoci. Magari possiamo mettere solo le prime 4 lettere del nome e cognome.)

MONICA: Nessuno tranne il Gestore Produttore nome15 (Iqbal) può modificare le date apertura e chiusura ordine.
CLAUDIO: per questo direi che ok così. Il referente produttore comanda!

MONICA:Se si avanza l'ordine in Giare Correggio come arrivato, consegnato, ecc., risulta allo stesso stato anche in Giare Camp9 e Iqbal. Non sono riuscita a modificare le quantità se, per esempio, un prodotto non arriva.
CLAUDIO: Effettivamente c'è un'operatività specifica per l'ordine (consegna, correzione prezzi, chiusura ordine, successivo aggiornamento della cassa)  che dipende dal singolo gruppo e quindi deve essere in carico all'INCARICATO dell'ordine. Il Supervisore potrebbe anche non essere al corrente di queste operazioni (anche se potrebbe essere interessante dargli la possibilità di seguirne l'esito). Ma pensiamoci.

Ora provo anche io a fare un ordine condiviso!! Bello!!!

**Comment by Jazzo** [comment]
>
> MONICA: Giare Camp9 ha impostato Alessandra Iori come referente interno.
> Però inizialmente Alessandra Iori non può gestire l’ordine che appare con
> referente ordine: nessun referente ordine assegnato!
> Gli utenti possono ordinare ugualmente (è ok?).
> CLAUDIO: Non è ok. L'ordine deve prima essere reso visibile
> dall'amministratore del Gruppo che assegna la gestione dell'ordine ad un
> INCARICATO (che potrebbe o no corrispondere col referente interno),
> Suggerisco che di default venga proposto il referente interno del
> produttore (o l'ultimo incaricato che ha gestito l'ordine?)
>
E' un bug. Non devono poter ordinare.
Sul default invece rimanderei alla versione Stable.

MONICA: TUTTI (nome15 + SuperAdmin Correggio + Barbara + Alessandra Iori)
> vedono lo stesso totale ordinato (dei 3 gas coinvolti?) e solo i nomi di
> chi ha ordinato nel proprio gruppo, gli altri ordini sono anonimi
> CLAUDIO: solo il referente produttore che ha creato l'ordine (direi ch
> el'abbiamo ribattezzato SUPERVISORE ORDINE) potrà vedere l'ordine completo
> (di tutti i 3 gas coinvolti: importi e utenti che hanno ordinato), forse
> meglio in un'area apposita di "gestione dell'ordine condiviso". (mi piace
> che gli utenti di altri gruppi siano anonimi per privacy , anche se
> potrebbe essere scomodo per capirsi in caso di domande sull'ordine.
> Pensiamoci. Magari possiamo mettere solo le prime 4 lettere del nome e
> cognome.)
>
Qui invece credo che Monica si riferisca ad un altro bug.
Ogni GAS dovrebbe vedere solo gli ordini dei propri utenti e invece vede
anche quelli degli altri (anche se in forma anonima). Questo però è un bug,
non è una funzionalità voluta. Poi possiamo discuterne ma lascerei comunque
l'esclusiva visualizzazione del TOTALE ordine di tutti i GAS al solo
Supervisore Ordine.




> MONICA:Se si avanza l'ordine in Giare Correggio come arrivato, consegnato,
> ecc., risulta allo stesso stato anche in Giare Camp9 e Iqbal. Non sono
> riuscita a modificare le quantità se, per esempio, un prodotto non arriva.
> CLAUDIO: Effettivamente c'è un'operatività specifica per l'ordine
> (consegna, correzione prezzi, chiusura ordine, successivo aggiornamento
> della cassa) che dipende dal singolo gruppo e quindi deve essere in carico
> all'INCARICATO dell'ordine. Il Supervisore potrebbe anche non essere al
> corrente di queste operazioni (anche se potrebbe essere interessante dargli
> la possibilità di seguirne l'esito). Ma pensiamoci.
>
Questo potrebbe essere un dramma.
Al momento è comunque *il Supervisore dell'ordine che muove lo Stato degli
Ordini*. Ovviamente ogni cambio di stato verrà appositamente segnalato ai
vari Incaricati e, per ogni stato, questi potranno effettuare le operazioni
(correzione prezzi, prodotti non disponibili, ecc).
Verifichiamo bene se questo punto può essere lasciato così perchè un
eventuale modifica non è cosa da poco perchè richiede lo spostamento dei
campi da una tabella all'altra e di conseguenza tutte le relative
funzionalità nel codice.
