### ISSUE TITLE
Listini Condivisi non visibili

### ISSUE THREAD

**Issue by claudiogiare** [iGruppi/iGruppi#36]
Non riesco a rendere visibile per il mio gruppo un listino che è stato condiviso da un altro gruppo.
Subito sembra accettare il VISIBILE=SI , dopo aver cliccato su SALVA, ma poi non è presente tra i listini disponibili per aprire un nuovo ordine e tornando a Gestione Listino, il flag VISIBILE è rimasto a NO.

**Comment by Jazzo** [comment]
Puoi darmi maggiori info:
- di che listino si tratta?
- qual è il tuo gruppo?

**Comment by claudiogiare** [comment]
Listino: Listino imported: RAVINALA SOC.COOP.SOCIALE    (del gruppo GAS Iqbal)
utente: email23
condiviso con un po' di altri Gruppi, tra cui Baragalla.

Poi vado in Baragalla con utente sarabiga[chiocciola]yahoo.it pwd: saracava, che è referente per RAVINALA e provo a flaggare VISIBILE a SI, nel listino condiviso, ma non va.

Non lo vedo quindi neanche tra i listini disponibili per creare nuovo ordine.

Non riesco a creare un nuovo ordine
