### ISSUE TITLE
Errore su apertura ordine

### ISSUE THREAD

**Issue by claudiogiare** [iGruppi/iGruppi#37]
Se provo ad aprire un ordine senza aver scelto un listino, mi dà un errore php.
ok, ma Sarebbe meglio gestirlo con un messaggio che mi avvisa di scegliere il listino.

**Comment by monicapgiare** [comment]
Questo è successo anche a me e ho notato che, tornando indietro, scegliendo un listino e salvando, vengono creati due ordini: uno corretto e uno che indica "nessuno" al posto del produttore:
![image](https://cloud.githubusercontent.com/assets/11527743/8659471/795c8084-29ab-11e5-81f9-7e434de01ab5.png)

Forse questo non dovrebbe succedere. 
Se non si può evitare e succede per errore, basterà impostare l'ordine non visibile e privato perchè nessuno lo veda più?

**Comment by Jazzo** [comment]
@monicapgiare confermo: non deve succedere. E' semplicemente da mettere a
posto.
