### ISSUE TITLE
Cambio prezzo di un prodotto all'interno dell'ordine

### ISSUE THREAD

**Issue by claudiogiare** [iGruppi/iGruppi#38]
Ho notato che cambiando un prezzo di un prodotto all'interno dell'ordine (nell'esempio da 40,50 a 55,50), aggiorna correttamente l'etichetta informativa (55,50€ a confezione), ma nel conteggio dell'importo viene considerato il prezzo originario (40,50)
![cambioprezzo](https://cloud.githubusercontent.com/assets/7717889/7012815/3291f628-dcb4-11e4-90a1-047da1d8a739.jpg)

**Comment by Jazzo** [comment]
Fixed. Prendeva il Costo Listino anzichè il costo Ordine.
