### ISSUE TITLE
Gestione Listini - Aggiornamento Prezzi (1) e Utente di creazione (2)

### ISSUE THREAD

**Issue by claudiogiare** [iGruppi/iGruppi#39]
Ciao.
1)
Ora riesco a creare un nuovo listino, ma appena modifico un prezzo e faccio SALVA, mi dice "Listino Aggiornato con successo!", ma non mi mantiene le modifiche.
2)
Inoltre quando vado nella "gestione ordini - Nuovo Ordine", le informazioni associate al listino (Creato da: e Ultimo Aggiornamento) non sono corretti o non funzionano.

Sono nel gruppo Baragalla - ho creato listino "Listino Nuovo" con l'utente sarabiga[chiocc]yahoo.it - il listino risulta, però, creato da un altro utente
![listino](https://cloud.githubusercontent.com/assets/7717889/7023264/207017a6-dd34-11e4-811a-b95d21bff4bb.jpg)

**Comment by Jazzo** [comment]
I dati nell'elenco Listini per Nuovo ordine ora sono corretti.
La data del Listino è aggiornabile tramite apposito pulsante:

![schermata 2015-04-15 alle 18 30 27](https://cloud.githubusercontent.com/assets/1465434/7163995/87e52998-e39d-11e4-9a92-3608beef1c9c.png)
