### ISSUE TITLE
Visualizzazione Ordini nella sezione "Gestione Ordini"

### ISSUE THREAD

**Issue by claudiogiare** [iGruppi/iGruppi#40]
Nella sezione "Gestione Ordini" è un po' scomoda la visualizzazione divisa per Ordini "Privati - Condivisi - Pubblici". col filtro per Stato Ordini obbligatorio.
![filtro_ordini](https://cloud.githubusercontent.com/assets/7717889/7023527/368bb39a-dd36-11e4-8147-ef39a7cd5f9c.jpg)

Il Referente Produttore probabilmente non avrà tanti ordini di diversa natura nella sua gestione.
Petanto basterebbe elencarli tutti in un'unica visualizzazione (in ordine cronologico) e distinguerli con un etichetta, magari colorata diversamente per ogni natura.

Stessa cosa nei Listini

**Comment by claudiogiare** [comment]
SI potrebbe pensare di inserire un contatore di fianco ad ogni opzione del filtro.
Esempio:
Ordini privati (0)
Ordini condivisi (3)
Ordini Pubblici (1)

**Comment by Jazzo** [comment]
![schermata 2015-08-21 alle 01 57 47](https://cloud.githubusercontent.com/assets/1465434/9398514/1f153768-47a8-11e5-8655-68d0f2692b7d.png)
