### ISSUE TITLE
Gestione Ordini - Problema su sconto in %

### ISSUE THREAD

**Issue by claudiogiare** [iGruppi/iGruppi#42]
![aggiornamentoprezziordine](https://cloud.githubusercontent.com/assets/7717889/7024191/3ff21e7e-dd3b-11e4-80e1-6875ece23221.jpg)
CI sono dei problemi nell'aggiornamento dei prezzi dei prodotti all'interno di un ordine.

Se cambio l'ordinamento dei prodotti elencati e poi aggiorno i prezzi di un prodotto (es. del primo di quell'ordinamento), l'aggiornamento non viene fatto su quel prodotto, ma sul primo della lista originaria (di default). E' come se "vincesse" la posizione nella lista e non il codice del prodotto.

Inoltre la colonna Sconto% non funziona bene:
- Se metto 5, mi scrive 500%
- se metto 0,5 , subito mi scrive correttamente 50%, ma rientrando nell'ordine successivamente trovo 100%

**Comment by Jazzo** [comment]
Resource: https://github.com/handsontable/handsontable/wiki/Understanding-column-sorting-plugin

**Comment by Jazzo** [comment]
Gestiremo lo Sconto in % in versione Stable, per ora bisognerà accontentarsi della spunta "Offerta" e di modificare il Prezzo. Il sistema potrà comunque verificare la differenza di Prezzo tra Listino e Ordine nel caso in cui è spuntato "Offerta".
