### ISSUE TITLE
Ordini MultiProduttore

### ISSUE THREAD

**Issue by claudiogiare** [iGruppi/iGruppi#43]
Negli ordini multiproduttore, potrebbe essere utile inserire l'informazione del produttore 
tra i filtri di ricerca o di fianco alla descrizione del prodotto.

Inoltre nella consultazione dell'ordine potrebbe essere utile avere il campo del produttore nella tabella per poter ordinare(sort) la lista in base a questo campo.

**Comment by claudiogiare** [comment]
potrebbe risultare utile dare un nome generico all'ordine.
es. ORDINE FERMENTO NATURALE
Attualmente viene fuori una etichetta "Ordine del gg/mm/aaaa" e l'elenco di tutti i produttori coinvolti. Se sono tanti, è di difficile lettura.
![schermata 07-2457220 alle 23 52 13](https://cloud.githubusercontent.com/assets/7717889/8736046/b4f2702e-2c15-11e5-8a44-df60e3528124.png)

**Comment by claudiogiare** [comment]
Filtri per categorie prodotti: attualmente moltiplica le categorie prodotto quanti sono i produttori anche se il nome è lo stesso
![schermata 07-2457221 alle 00 11 18](https://cloud.githubusercontent.com/assets/7717889/8736355/0c321e78-2c18-11e5-8f75-0b3ee5bcfe34.png)

**Comment by claudiogiare** [comment]
ERRORE NEL CALCOLO DELL'IMPORTO ORDINATO
Non effettua il calcolo dell'importo (prz*qtà) per i prodotti gestiti A CONFEZIONE, se nello stesso ordine MULTIPRODUTTORE sono presenti altri prodotti gestiti PER PEZZATURA!!

ATTENZIONE l'anomalia si verifica anche per un ordine monoproduttore in genere (forse il problema è nella presenza della pezzatura per Litro)

**Comment by claudiogiare** [comment]
Non calcola la QTA REALE per questi casi. La lascia a zero e quindi non riesce a fare il calcolo

**Comment by marcenuc** [comment]
@claudiogiare, è molto probabile che il problema sia quello che spiegavo a @flavio57 in https://github.com/iGruppi/iGruppi/issues/63#issuecomment-117345090 cioè il `moltiplicatore` è a 0. In pratica questo succede perché il moltiplicatore non viene chiesto quando si sceglie la gestione `A CONFEZIONE`, e così rimane a 0, ma viene comunque usato nel calcolo del totale, quindi annulla la riga.

**Comment by claudiogiare** [comment]
Chiudo l'issue perchè è stato splittato in diversi issue più specifici (vedi riferimenti sopra)
