### ISSUE TITLE
Gestione listini: IRIS impossibile importare prodotti

### ISSUE THREAD

**Issue by davidepigoni** [iGruppi/iGruppi#44]
Ho provato a creare vari listini con differenti referenti e provando con diversi utenti (per es.: vedi IRIS)
Non riesco però ad importare nessun prodotto per poter poi procedere alla creazione dell'ordine:

![listini_importare_prodotti](https://cloud.githubusercontent.com/assets/630153/7057003/6d6639be-de51-11e4-90ca-76757434dd34.png)

**Comment by Jazzo** [comment]
In realtà quando crei un listino dovrebbe importare automaticaticamente
tutti i prodotti attivi in Anagrafica.
Fino ad un paio di giorni fa questa cosa non funzionava però poi l'ho
sistemata.
Questo listino lo hai creato in questi giorni?
Prova a crearne un altro in modo da verificare che il problema
dell'importazione dei prodotti dall'Anagrafica, quando crei un nuovo
Listino, sia risolto.

Il giorno 9 aprile 2015 00:44, Davide Pigoni <notifications@github.com> ha
scritto:

> Ho provato a creare vari listini con differenti referenti e provando con
> diversi utenti (per es.: vedi IRIS)
> Non riesco però ad importare nessun prodotto per poter poi procedere alla
> creazione dell'ordine:
>
> [image: listini_importare_prodotti]
> <https://cloud.githubusercontent.com/assets/630153/7057003/6d6639be-de51-11e4-90ca-76757434dd34.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iGruppi/iGruppi/issues/44>.
>



-- 
Davide Gullo, Consulente Web (professionista disciplinato ai sensi della
legge 4/2013)
http://www.m4ss.net
gullo@m4ss.net

**Comment by claudiogiare** [comment]
Ci siamo appena accorti che è ricapitato anche a noi.
O meglio.
Con un utente (iotti.valeria@gmail.com) che è stato impostato come referente sia di Saponaria che di Rob del bosco per il gruppo "Baragalla":
- abbiamo creato un nuovo listino per Saponaria e tutto ok: ha impostato in automatico tutti i prodotti presenti in anagrafica
- successivamente ho provato a creare un nuovo listino sul produttore Rob del bosco e la situazione è quella che segnala Davide (con tutti gli articoli da importare)

**Comment by Jazzo** [comment]
Ok, importazione sistemata!

**Comment by Jazzo** [comment]
Risolto anche il problema che si è verificato su Rob.
In realtà l'importazione iniziale (in fase di creazione nuovo Listino) ha funzionato bene in quanto importa solo i prodotti **Attivi** in Anagrafica ma Rob ha tutti i prodotti **NON attivi** e quindi non ha importato nulla. Li vedevate come "Nuovi prodotti" da importare causa un bug che ora ho sistemato.
