### ISSUE TITLE
movimenti gestione cassa

### ISSUE THREAD

**Issue by monicapgiare** [iGruppi/iGruppi#45]
Tutti i contabili di tutti i gruppi vedono gli stessi movimenti che riguardano utenti dei diversi gruppi.
Questo è un esempio ma sono tutti così.
Per esempio, nessuno di questi utenti è delle Giare Correggio.

![image](https://cloud.githubusercontent.com/assets/11527743/7141199/4737fe48-e2d0-11e4-896e-98b8fa2e96ea.png)

**Comment by monicapgiare** [comment]
Se fosse possibile, sarebbe utile una tabella per consultare i movimenti ordinandoli per utente o per produttore/ordine o per data, producendo dei subtotali.
Mentre per i singoli utenti sono utili i movimenti in entrata ed in uscita di ognuno (come nella homepage), al tesoriere del gruppo servono anche i totali appunto per gruppo, soprattutto degli ordini che dovrebbero corrispondere alle fatture da pagare.

**Comment by Jazzo** [comment]
Ok, sistemata visualizzazione cassa: elenca i movimenti dei soli utenti appartenenti al Gruppo del Tesoriere.

**Comment by claudiogiare** [comment]
Forse potremmo anche per il contabile preparare delle "viste" già pronte (che poi sono delle Query):
- Movimenti per utente (ordinati per utente)
- Movimenti per utente (ordinati per data)
- Movimenti per ordine (ordinati per data)
-Movimenti per ordine (ordinati per produttore)
Che ne dite?
Ciao

**Comment by Jazzo** [comment]
<gullo@m4ss.net>
Ok i movimenti Ordine.

I "Movimenti per utente (ordinati per data)" è la visualizzazione attuale.
Per quelli utente invece non è meglio creare una sorta di filtro per utente
singolo? Nel senso che se ordino per utente ma devo vedere l'utente Zoppi
non mi passa più. O sbaglio?

**Comment by monicapgiare** [comment]
Non so rispondere a proposito di ordinamenti, query, filtri ... finchè non vedo degli esempi. Credo che piuttosto che ordinare i movimenti, come avevo chiesto, in effetti possano essere più utili dei filtri che permettano di vedere solo un utente o solo un ordine.

Mi è appena venuto in mente che una cosa importante che sarebbe utile che il contabile vedesse facilmente è il riepilogo dei saldi degli utenti del suo gruppo.
Per esempio, per vedere chi è in rosso ed eventualmente mandare un promemoria. A meno che questo mitico sistema possa farlo in automatico al raggiungimento di una certa soglia ...

**Comment by Jazzo** [comment]
Ok Monica, questi son tutti filtri (da realizzare ma relativamente
semplici).
Mettiamoli in fila qui spiegandoli bene (come hai già fatto) e poi li
implementiamo tutti.
