### ISSUE TITLE
Stato Ordine: CONSEGNATO

### ISSUE THREAD

**Issue by claudiogiare** [iGruppi/iGruppi#46]
Mi è sembrato di capire che SOLO in questo stato è possibile modificare le qtà dell'ordine 

1) BUG: In verità la modifica delle Qtà (all'interno della sezione "Quantità Ordinate" non viene salvata

2) QUESTION: Secondo me, manca una modalità di  comunicare OK da parte dell’incaricato, dopo che ha corretto i prezzi e qtà prima dell’attesa di archiviazione.
Forse si potrebbe gestire l’abilitazione alla verifica Qtà nel precedente stato "Arrivato" e quando l’incaricato chiude definitivamente il tutto, clicca su "-->CONSEGNATO" e la palla passa al Contabile, che vede lo stesso ordine come "In Attesa di archiviazione".
Quindi CONSEGNATO e "IN ATTESA DI ARCHIVIAZIONE" di fatto coincidono.

3) QUESTION:  Anche la funzione di Ripartisci Spese così mi sembra un po' troppo “aperta”. Cioè secondo me andrebbe un po’ protetta/limitata, rendendola gestibile solo in determinati stati (es. solo consegnato o arrivato.. solo uno dei due)

**Comment by Jazzo** [comment]
Per me OK sui 2 question.

**Comment by Jazzo** [comment]
Fixed 1

**Comment by Jazzo** [comment]
Ok punto 2. Ora la modifica Qta (a carico dell'Incaricato Ordine interno al Gruppo) è disponibile sullo stato "Arrivato" (e non più sul Consegnato).

**Comment by Jazzo** [comment]
Ok punto 3. La gestione Spese Extra è sempre a cura dell'Incaricato Ordine e gestibile **esclusivamente** nello Stato "Arrivato".
