### ISSUE TITLE
descrizione prodotto in archivio prodotti

### ISSUE THREAD

**Issue by monicapgiare** [iGruppi/iGruppi#56]
Per il produttore Cerutti, dall'elenco dell'archivio prodotti si vede la descrizione delle farine completa:

![image](https://cloud.githubusercontent.com/assets/11527743/7666936/62821c88-fbf8-11e4-8d47-c677dcfdd1e6.png)

Ma entrando nel dettaglio si vede solo una parte della descrizione:

![image](https://cloud.githubusercontent.com/assets/11527743/7666938/820e486a-fbf8-11e4-9faf-30cca6169049.png)

Se esco senza modificare niente, la descrizione rimane completa. Se modifico per esempio il prezzo e salvo, la descrizione diventa incompleta anche nell'elenco.

Forse dipende dalle virgolette? Altre descrizioni lunghe ma senza virgolette, come quelle del riso, non cambiano nell'elenco e nel dettaglio.

**Comment by monicapgiare** [comment]
In effetti, ho provato senza virgolette e questo inconveniente non succede più.

**Comment by marcenuc** [comment]
Il baco è nella libreria Savant3 usata da MyFw che non fa l'html escape dei valori quando costruisce l'HTML del campo di input.

Non ho trovato un gestore dei bachi di Savant3, ma credo si possa ovviare in MyFw facendo l'escape dei valori prima di passarli alla libreria.

**Comment by Jazzo** [comment]
thanks @marcenuc
