### ISSUE TITLE
Visibilità Ordine

### ISSUE THREAD

**Issue by claudiogiare** [iGruppi/iGruppi#57]
Sembra non recepire la scelta visibile SI - NO di un ordine all'interno di un gruppo.

Cioè se creo un ordine e lo condivido con un altro gruppo, gli utenti di quel gruppo risultano già abilitati all'ordine.
Ci vuole un passaggio (da amministratore) che obbliga a rednere l'ordine visibile e assegna un utente del gruppo come incaricato all'ordine

**Comment by Jazzo** [comment]
Il problema è nell'area "Ordina", gli utenti vedono comunque un ordine anche se ancora NON è visibile.
L'errore sta nella query "getAllByIdgroupWithFilter": non include il flag "og.visibile='S'".
