### ISSUE TITLE
Pagina Gestione Ordini

### ISSUE THREAD

**Issue by claudiogiare** [iGruppi/iGruppi#58]
Inseriamo un filtro per STATO AVANZAMENTO ORDINE (Pianif .- Aperto - Chiuso-....)
Di default si visulaizzano  solo gli aperti, ma col filtro si possono selezionare quelli in altri stati.

Sparisce il filtro per Ordine Privato, Condiviso o Pubblico : questa informazione la portiamo di fianco o sotto la descrizione di ogni ordine.

**Comment by Jazzo** [comment]
![schermata 2015-08-21 alle 03 18 01](https://cloud.githubusercontent.com/assets/1465434/9399369/9a9d3312-47b3-11e5-997b-363e60734d9b.png)

**Comment by monicapgiare** [comment]
Io non vedo l'elenco degli ordini come nell'immagine sopra ma così

![image](https://cloud.githubusercontent.com/assets/11527743/9816002/83651bb8-589a-11e5-8776-bb885409c27d.png)

Personalmente penso che l'informazione più importante di questo elenco sia il nome del produttore. Nella versione sopra era in grassetto e risaltava un po' di più, anche se lo preferirei più grande. Nella versione attuale si vede poco, secondo me.
Mentre il nome dell'ordine e le caselle "condiviso/privato/pubblico", sempre secondo me, sono meno importanti.

**Comment by Jazzo** [comment]
La schermata sopra è precendente all'aggiornamento #43 con l'inserimento del "Nome ordine".
Il pulsante è bianco in versione "mono produttore" e arancione in "multi produttore" (con relativo menù a tendina con i vari produttori). E' un pulsante perchè è già previsto in futuro la possibilità di cliccare per accedere direttamente alla scheda Produttore. Si può ingrandire, certo, ma in questa fase potete anche ripetere il produttore nel nome dell'ordine, es: "Settembre CERUTTI". 
Al momento è utilizzato uno "schema" che contempla tutte le casistiche, che non son poche: multiproduttore con nome, multiproduttore senza nome, condivisioni, ecc. Se vogliamo possiamo rivedere questo schema ma facciamolo insieme al primo incontro.
