### ISSUE TITLE
Primo accesso non funziona

### ISSUE THREAD

**Issue by flavio57** [iGruppi/iGruppi#63]
Ho installato la versione 2.0 beta ma non riesco a farla funzionare.
Quando accedo ricevo il messaggio:
-----------------------------------------------
Siamo spiacenti, si è verificato un errore...
Errore 404: Pagina non trovata!
La pagina richiesta non è disponibile.
-----------------------------------------------
Inoltre se clicco su Login o "Nuovo Utente" ricevo l'errore:
Not Found
The requested URL /auth/login was not found on this server.

Come posso risolvere questi problemi? Nei log del server apache non vedo segnalato nulla.
Grazie
Flavio

**Comment by marcenuc** [comment]
Dal messaggio di errore, direi che quasi sicuramente devi configurare correttamente il server HTTP.

Ho troppe poche informazioni per darti una risposta precisa. Dovrei sapere almeno che server usi (Apache, Nginx, ...); dove hai fatto l'installazione (spazio web condiviso, sul tuo computer, ...); se possibile, la configurazione del virtualhost.

Comunque le cose importanti da guardare sono:

- la document root deve essere la cartella `public`, **non** la radice del progetto;
- devi configurare il server in modo che passi tutte le richieste allo script `index.php` dentro `public`;
- conviene impostare la variabile di ambiente `APPLICATION_ENV` a `development` per avere messaggi di errore più utili.

Un esempio di configurazione, per Apache, lo trovi nel file `public/.htaccess`.

Io, invece, ho disabilitato `.htaccess`, e uso la seguente configurazione del virtual host di Apache **2.4**:

```apache
<VirtualHost *:80>
    ServerAdmin marcello@example.com
    ServerName igruppi.example.com

    DocumentRoot "/path/to/iGruppi/public"
    <Directory "/path/to/iGruppi">
      Options FollowSymLinks
      AllowOverride None

      Require all granted

      RewriteEngine On
      RewriteRule ^index\.php$ - [L]

      RewriteCond %{REQUEST_FILENAME} !-f
      RewriteCond %{REQUEST_FILENAME} !-d
      RewriteRule . /index.php [L]
    </Directory>

    SetEnv APPLICATION_ENV development
</VirtualHost>
```

**Comment by Jazzo** [comment]
Ottimo @marcenuc ;-)
@flavio57 vedi anche altre risorse #1

**Comment by flavio57** [comment]
Ho installato su un mio pc linux ed uso Apache.
La document root è la cartella public, ma non ho configurato il server come
da te suggerito nel punto 2 (anche perche' non sapevo di doverlo fare ;-))
Provo e poi ti faccio sapere.


Il giorno 29 giugno 2015 09:35, Marcello Nuccio <notifications@github.com>
ha scritto:

**Comment by flavio57** [comment]
@marcenuc: Grazie! Ho messo la configurazione che mi hai suggerito del VirtualHost e così ho risolto il primo problema. Purtroppo ho ancora gli altri 2 problemi, quelli relativi a "Login" e "Nuovo Utente", puoi darmi qualche altro suggerimento? Chi o cosa dovrebbe essere attivato con quei path (/auth/login) ? Se anche riuscissi a farli funzionare c'e' un login di default da utilizzare per connettersi?
Pensi che manchi qualche modulo di apache? La versione che ho installato è:
Server version: Apache/2.4.7 (Ubuntu)
Grazie in anticipo.

**Comment by marcenuc** [comment]
@flavio57, ho ancora troppe poche informazioni per risponderti, ma prima di tutto ti do un avvertimento: la versione 2 di iGruppi è poco più di un prototipo. Cioè: funziona abbastanza da poter essere usata per fare degli ordini (io la sto usando per alcuni ordini del mio GAS), ma noterai facilmente diversi comportamenti strani o pezzi mancanti che probabilmente ti aspetteresti di trovare.

Tra le funzionalità mancanti, per esempio, ci sono:

  - una procedura di installazione automatica;
  - un'interfaccia di amministrazione.

Questo vuol dire che:

  - le tabelle del database devi crearle caricando il dump SQL che trovi in [documentation/database/igruppi_dump_2.sql](https://github.com/iGruppi/iGruppi/blob/branch-2.0/documentation/database/igruppi_dump_2.sql) usando un qualsiasi client MySQL (la linea di comando, [MySQL Workbench](http://dev.mysql.com/doc/workbench/en/index.html), [phpMyAdmin](http://www.phpmyadmin.net/), [Adminer](http://www.adminer.org/), quello che ti pare...);
  - il database che viene creato è vuoto, quindi il primo utente devi inserirlo a mano tu nella tabella `users`, sempre usando il tuo client preferito;
  - lo stesso discorso vale per le tabelle `categorie`, `categorie_sub`, `groups`, `users_group`. Cioè: la base dati iniziale, va inserita a mano direttamente nel database. Dopo alcune cose riesci a farle da programma, ma la partenza è manuale.

Se ancora non ti sei spaventato, ti aiuto molto volentieri. Ma ti avviso che il "servizio di assistenza" in questo periodo non funziona tanto bene: io fra una settimana parto e devo prima finire un bel po' di lavori; @Jazzo, il creatore di iGruppi, è ancora più impegnato come puoi intuire dalle poche e telegrafiche risposte.

**Comment by flavio57** [comment]
Il DB l'ho creato e caricato con il dump SQL igruppi_dump.sql  (non '_2' che mi pare non ci sia... ma potrei sbagliarmi visto che adesso non sono davanti al PC dove l'ho installato), e il fatto di caricare a mano non mi spaventa piu' di tanto.. a me interessa dare un'occhiata all'interfaccia e alle funzionalita' per capire se potrebbe andar bene anche per il nostro GAS. Capisco che il periodo non sia dei migliori ma se riuscissi a farlo funzionare poi in qualche modo con le tabelle mi arrangio. Potrei mandarti l'output del phpinfo() per darti tutte le informazioni sul mio sistema ma non so come inviartelo (qui si puo' solo inserire immagini)... dimmi tu
Un'altra cosa, possono entrarci i permessi sul File System? Io per non sbagliare ho messo rw per tutti.
In ogni caso grazie per la tua disponibilita'.

**Comment by flavio57** [comment]
Sono riuscito ad installarlo e farlo funzionare su Linux Fedora.. ma forse è la versione 1.4 perche' non vedo alcune caratteristiche descritte nella 2.0: gestione cassa, non c'e' la figura del referente ma solo o User o Admin,..  è giusto? O ancora non ci sono quelle funzionalita'?

**Comment by marcenuc** [comment]
@flavio57, se non trovi il file `igruppi_dump_2.sql`, probabilmente è perché sei sul [branch sbagliato](https://github.com/iGruppi/iGruppi/branches). Avevo messo il link al file proprio per farti vedere dove trovarlo.

Il branch `master` contiene la versione 1.4, che è quella attualmente usata dal GAS di @Jazzo, ed allineata al `branch-1.4`. Il dump da usare per questa versione è `igruppi_dump.sql`

Il branch `branch-2.0` contiene l'**anteprima** di quello che sarà la 2.0, ed è quella che uso io per alcuni ordini del mio GAS. Il dump per questa versione è `igruppi_dump_2.sql`.

Riguardo le funzionalità che cerchi, da quel che so ci sono solo nella 2.0, ma non so risponderti con sicurezza perché io sono letteralmente l'ultimo arrivato in questo progetto, quindi non ho una completa conoscenza di tutto.

Io sto usando la 2.0, invece della più stabile 1.4, perché sono un programmatore e, provandola sul campo, posso dare una mano correggendo i problemi che trovo. Puoi vederlo dalle [pull request](https://github.com/iGruppi/iGruppi/pulls) che ho fatto. Purtroppo però @Jazzo in questo momento è troppo impegnato per darci un'occhiata e quindi son ferme lì.

La situazione si sbloccherà perché ci sono diversi altri GAS coinvolti in questo progetto, quindi prima o poi si troveranno il tempo e le risorse per andare avanti, ma per ora le cose vanno a rilento.

**Comment by flavio57** [comment]
ok, ti ringrazio. Mi scarichero' la 2.0 e riprovero' ... cmq la 1.4 mi e' servita per rodarmi, in qualche modo sono riuscito ad usarla. Grazie!

**Comment by flavio57** [comment]
Ho messo in funzione la 2.0.. qualcosa sono riuscito a fare (inserire degli utenti, produttori, categorie,..) ma non avendo la documentazione delle tabelle sono andato un po' ad intuito e qualche problema ce l'ho ancora: non riesco a creare un listino (nella 1.4 c'ero riuscito, avevo anche aperto un ordine..),  non riesco ad usare la cassa (ma non so a che punto è lo sviluppo..)... comunque l'interfaccia mi sembra carina, ma ho l'impessione che ci sia ancora un bel po' di lavoro da fare...

**Comment by marcenuc** [comment]
@flavio57, su questo non c'è dubbio: c'è ancora un bel po' di lavoro da fare! È per questo che ti ho avvertito di trattarlo come un prototipo, più che come una beta come siamo abituati a pensarla oggi.

Su un'altra cosa non c'è dubbio: entro quest'anno migliorerà molto, perché diversi GAS hanno in programma di usarlo, e quindi c'è un discreto interesse per farlo funzionare decentemente.

Se hai fretta di avere qualcosa di funzionante, secondo me ti conviene rimanere sulla 1.4. Se non hai tanta fretta e magari sai programmare e/o fare dei buoni bug report per risolvere un po' di problemi, vai con la 2.0... ma aspettati un luglio un po' freddino come supporto tecnico... ;-)

**Comment by Jazzo** [comment]
@flavio57 in realtà ci sono già molte cose che chiedi:
* guarda la [sezione Ruoli nel wiki](https://github.com/iGruppi/iGruppi/wiki/Ruoli), trovi l'elenco dei diversi ruoli e come questi sono gestiti a livello di DB
* struttura database: [schema EER versione 2.0](https://github.com/iGruppi/iGruppi/blob/master/documentation/database/iGruppi_2-0.mwb) (Mysql workbench), qui in allegato trovi il PDF
* la [Gestione Cassa](https://github.com/iGruppi/iGruppi/wiki/Gestione-Cassa) nella versione 2.0 è implementata in parte, leggi #45 e #47 per tutto ciò a cui stiamo lavorando/studiando
* documentazione [wiki per Listini](https://github.com/iGruppi/iGruppi/wiki/Listini) per farti un'idea su come gestiamo a livello di DB le cose, il che ti sarà sicuramente di aiuto per aprirne uno ;-)

@marcenuc invece sarà un Luglio molto caldo!! ;-)

[iGruppi_EER_2-0-rev12.pdf](https://github.com/iGruppi/iGruppi/files/402/iGruppi_EER_2-0-rev12.pdf)

**Comment by marcenuc** [comment]
@Jazzo, allora ci sei! Pensavo che luglio preferissi passarlo in barca! ;-)

Per quel che ne so, il mio GAS attualmente è l'unico ad usare iGruppi 2.0, o sbaglio?

La mia esperienza finora è che alla fine si riesce a farlo andare, ma è pieno di problemini (prodotti che non si vedono, totali che non si aggiornano, tasti che non funzionano, ...) che possono mettere in difficoltà l'utente non abbastanza motivato. Per questo motivo, per ora, consiglio di usare la 1.4 per chi ha fretta. Ma se per luglio @Jazzo torna operativo, allora è tutta un'altra storia! ;-)

**Comment by flavio57** [comment]
@Jazzo GRAZIE mille!! Così è molto meglio... adesso comincio a divertirmi un po', le tue informazioni sono state utilssime.. vedo cosa riesco a combinare. Per adesso grazie di nuovo e ciao (fino al prossimo dubbio). Ah! Un'ultima cosa come si fa per sapere quando ci sono degli aggiornamenti in modo da rimanere allineati con gli sviluppi? Noi (nel senso di GAS) non abbiamo particolarmente fretta ma almeno personalmente sono molto interessato e piu' avanti potrei coinvolgere anche gli altri del mio gruppo

**Comment by flavio57** [comment]
@Jazzo penso che @marcenuc abbia ragione, nelle poche prove che ho fatto stasera anch'io ho visto totali che non si aggiornano o prodotti che non si vedono.. continuo con i miei test...

**Comment by marcenuc** [comment]
@flavio57:

 - per i totali che non si aggiornano, devi controllare che il campo `moltiplicatore` nella tabella `prodotti` sia impostato a `1.0`. Di default viene messo a `0` e quindi il totale non si aggiorna per ovvi motivi. È un problema noto, ma per il quale non ho avuto tempo di preparare una patch;
 - per i prodotti che non si vedono, dovrebbe essere sufficiente applicare le pull request #60 e #62. Purtroppo @Jazzo non ha avuto tempo di darci un'occhiata per integrarle o correggerle, quindi non ti garantisco che siano corrette, ma sul mio server le sto usando e funzionano (insiema alla #61).

Poi ci sono vari altri piccoli problemi, ma con questi accorgimenti dovresti come minimo essere in grado di creare un semplice ordine, consentire agli utenti di ordinare e vedere i totali generali e per utente.

**Comment by flavio57** [comment]
@marcenuc sì con il moltiplicatore ad 1.0 funziona (per i prodotti per adesso non ho fatto nulla).
Sono riusciito a simulare un'apertura di un ordine e a fare degli ordini.
@Jazzo magari è gia' previsto, quando viene fatto il Riepilogo Totale ordinato viene visualizzato solo il numero di colli, sarebbe meglio vedere quali sono i colli ordinati e le rispettive quantita'

**Comment by Jazzo** [comment]
<gullo@m4ss.net>
@flavio57 si, è previsto. Per avere un'idea di quali siano le nuove
funzionalità (ma anche le anomalie segnalate) ti consiglio di consultare la
sezione issues (magari cercando in modo mirato). Nel caso non trovassi
nulla ti chiedo allora di aggiungere la tua richiesta alle altre in modo da
averle tutte catalogate. Grazie mille!
