### ISSUE TITLE
VISUALIZZAZIONI Riepilogo Ordine

### ISSUE THREAD

**Issue by claudiogiare** [iGruppi/iGruppi#65]
Potremmo includere queste possibili tipologie di visualizzazione:

1. TOTALE ORDINATO 
riporta l’elenco dell’ordinato aggregato di ogni prodotto, senza il dettaglio dell’utente. In sezione viene riportato il produttore, in fondo il totale per ogni produttore.
Questa è la visualizzazione potrebbe essere utile al referente da inviare al produttore.
![image](https://cloud.githubusercontent.com/assets/7717889/9070429/e4372e04-3aef-11e5-96a2-a34420d5cbc4.jpg)

È utile riportare anche il codice prodotto.

2. PARZIALI UTENTI/PRODOTTI 
Tabella con campi: gruppo - utente - produttore - prodotto - qta ordinate
sarebbe MOLTO UTILE poter ordinare (sort) per utente o per prodotto (così si avrebbe la lista di tutti gli utenti che hanno ordinato uno specifico prodotto)
Sarebbe utile trovare un modo per  filtrare i dati cliccando sulle linguette di ogni colonna, come Excel.
![image](https://cloud.githubusercontent.com/assets/7717889/9070583/ccfaca6a-3af0-11e5-905f-9e4fee1d409a.jpg)

3. DETTAGLIO UTENTI 
l’utente è in sezione e sotto viene riportata la lista del suo ordine → Di fianco al nome dell’utente è utile  aggiungere le info di contatto
![image](https://cloud.githubusercontent.com/assets/7717889/9070767/ceede900-3af1-11e5-980b-2d195234fae0.jpg)

PER CIASCUNA DI QUESTE VISUALIZZAZIONI, solo per gli ordini condivisi e solo per alcuni ruoli (supervisore ordine, fondatore, tesoriere), sarà possibile scegliere da un menu a tendina le modalità di visualizzazione:
- TUTTI i GRUPPI (aggregato)
- scelta del SINGOLO GRUPPO tra tutti quelli che hanno partecipato all’ordine (inserire nella lista tutti i gruppi, anche quelli per cui  nessun utente del gruppo ha ordinato, così si può avere a disposizione la situazione completa)

In più solo per la visualizzazione 1.TOTALE ORDINATO può essere utile un’estrazione con TUTTI I GRUPPI in sezione, come questa:
![image](https://cloud.githubusercontent.com/assets/7717889/9071151/f619a198-3af3-11e5-8905-0a9cc647c1ca.jpg)

Valutare la possibilità di inserire informazioni aggiuntive (utili per la gestione operativa dell’ordine): 
- NOTE DI CONSEGNA; 
- NUMERI DI TELEFONO DEGLI UTENTI CHE HANNO ORDINATO
- NUMERO DI TELEFONO IN ALTO DELL’INCARICATO ALL’ORDINE E/O DEL REFERENTE PRODUTTORE
- NOTE DELL’ORDINE: sarebbe utile che fosse possibile inserire delle Note per l’ordine, che il supervisore potrebbe compilare e automaticamente vengono ereditate da tutti i gruppi che partecipano all’ordine condiviso

La query di riferimento è questa:
/* QUERY per estrarre le informazioni di un ORDINE CONDIVISO (MULTIGAS) e MULTIPRODUTTORE con prezzi*/
select distinct p.idprodotto, u.iduser, pr.ragsoc as PRODUTTORE, o.idordine, g.nome as GRUPPO, concat(u.nome,' ',u.cognome) as GASISTA, u.email as MAIL_GASISTA, /*u.tel as TEL_GASISTA,*/
p.codice as CODICE_PRODOTTO, p.descrizione as PRODOTTO, p.udm, p.aliquota_iva,
oup.qta, oup.qta_reale, op.costo_ordine, op.offerta_ordine, op.sconto_ordine, op.disponibile_ordine,
concat(uslave.nome,' ',uslave.cognome) as INCARICATO_ORDINE, uslave.email as MAIL_INCARICATO /*uslave.tel as TEL_INCARICATO,*/ ,
concat(umas.nome,' ',umas.cognome) as RESPONSABILE_ORDINE, umas.email as MAIL_RES_ORDINE /*umas.tel as TEL_RES_ORDINE,*/
from  ordini o
join ordini_groups og on og.idordine=o.idordine
join groups g on og.idgroup_slave=g.idgroup
left join users uslave on og.iduser_ref=uslave.iduser
join (select idordine, iduser_ref, idgroup_master from ordini_groups where idgroup_master=idgroup_slave) omaster
on omaster.idordine=o.idordine
join users umas on omaster.iduser_ref=umas.iduser
left join ordini_user_prodotti oup on oup.idordine=og.idordine
left join users u on oup.iduser=u.iduser
left join users_group ug on u.iduser=ug.iduser
join groups ugas on ug.idgroup=ugas.idgroup and ugas.idgroup=g.idgroup
left join prodotti p on oup.idprodotto=p.idprodotto
left join produttori pr on p.idproduttore=pr.idproduttore
join ordini_prodotti op on o.idordine=op.idordine and oup.idprodotto=op.idprodotto and oup.idlistino=op.idlistino
where op.idordine=16
Order by PRODUTTORE, GRUPPO, GASISTA, CODICE_PRODOTTO

**Comment by claudiogiare** [comment]
E’ utile anche visualizzare l’IMPORTO NETTO PER OGNI PRODOTTO ed il totale finale per facilitare la quadratura con alcune fatture che gestiscono l’Iva in fondosul Tot dell’imponibile (es.Iris)

**Comment by Jazzo** [comment]
Ora il Supervisore Ordine può visulizzare il Totale ordinato e Parziale utenti per singolo Gruppo:

![schermata 2015-09-10 alle 14 51 43](https://cloud.githubusercontent.com/assets/1465434/9789154/97a55fa6-57ce-11e5-9d7b-e9cba089a77e.png)





Resta da implementare la visualizzazione totale per Multigruppo:

![schermata 2015-09-10 alle 15 15 11](https://cloud.githubusercontent.com/assets/1465434/9789194/d0cfc3f2-57ce-11e5-8b57-343cf53df620.png)

**Comment by claudiogiare** [comment]
Meravigliose le viste per singolo Gruppo!!
Forse sarebbe utile per il Supervisore riuscire a vedere anche le informazioni (Nome, tel, mail) dei vari incaricati dei gruppi coinvolti nell'ordine...
In verità al momento non mi sembra che il supervisore possa avere queste informazioni da nessuna parte in iGruppi, giusto?
Se nel dettaglio di ogni gruppo possa apparire questa info, sarebbe sicuramente utile per la gestione logistica dell'ordine... 
Poi un domani pensiamo ad un sistema di messagistica automatica ;-)

**Comment by Jazzo** [comment]
Ho completato le viste del Supervisore ordini, sia Totale che Parziali utenti.
Inoltre ho aggiunto nelle viste per gruppi i dati degli utenti (indirizzo, email, ecc) e quelli dell'incaricato ordine.
