### ISSUE TITLE
Visibilità LISTINI (ex #33)

### ISSUE THREAD

**Issue by claudiogiare** [iGruppi/iGruppi#69]
Riporto da issue #33 
Se un listino è impostato a VISIBILE = NO oppure c'è un periodo di validità già passato, il listino continua ad essere visibile a tutti gli utenti all'interno dell'area di consultazione dei Listini. Invece dovrebbe rimanere visibile solo al Referente (o a chi l'ha creto?).

Per quanto riguarda, invece, la visibilità del listino, quando si crea un nuovo ordine (nell'area Gestione Ordini), risulta funzionante la funzionalità VISIBILE=SI o NO, mentre non il periodo di validità (quindi il listino non viene "bloccato", in caso di periodo passato).

**Comment by Jazzo** [comment]
Analizzando il problema per l'area Gestione Ordini ho scoperto un buco enorme... :-(
I listini pubblici vengono classificati tramite il campo listini.condivisione (PRI, SHA o PUB). Nel caso di PRI (Privato) e SHA (Condiviso) vengono aggiunti 1 o più record nella tabella listini_groups mentre per il PUB (Pubblico) non viene aggiunto alcun record. Sui listini pubblici però in questo modo non riesco a gestire VISIBILITA' e VALIDITA', campi gestiti nella tabella listini_groups in quanto specifici di ogni gruppo. Sulla Visibilità potremmo anche soprassedere considerando un Listino PUB (Pubblico) come sempre visibile, ma la VALIDITA'?

**Comment by Jazzo** [comment]
La soluzione che per ora ho messo in campo è che nei listini PUB (Pubblici), a differenza di quelli PRI (Privati) o SHA (Condivisi), i campi VISIBILITA' e VALIDITA' vengono impostati per tutti dal referente del gruppo che ha creato il listino. Per ora, con questa struttura di database, non abbiamo alternative.

**Comment by monicapgiare** [comment]
Ho notato che, impostando un periodo di validità per un listino e condividendolo, questo periodo di validità non è visibile per il referente del gruppo che ha "ricevuto" il listino e può gestirlo. Gli utenti di questo gruppo vedono addirittura "validità: sempre" visualizzando il listino.

![image](https://cloud.githubusercontent.com/assets/11527743/9721109/d3727c8e-5595-11e5-8699-12733f32c73b.png)

Mentre nel gruppo del referente che ha creato il listino e impostato la validità, gli utenti vedono il periodo di validità:
![image](https://cloud.githubusercontent.com/assets/11527743/9721145/20c93c70-5596-11e5-8a9d-71d047774a99.png)

Può essere corretto che la validità sia impostata solo da chi ha creato il listino, ma forse dovrebbe essere visibile a tutti.

**Comment by Jazzo** [comment]
Il funzionamento è corretto nel senso che ogni gruppo a cui viene condiviso il listino può gestirne in autonomia validità e visibilità. Al momento le impostazioni di default, quando viene condiviso un listino, sono: Validità SEMPRE, Visiblità NO.
Possiamo cambiarle come preferiamo.
