### ISSUE TITLE
Eliminazione prodotti da Listini esistenti (ex #33)

### ISSUE THREAD

**Issue by claudiogiare** [iGruppi/iGruppi#71]
Riporto da #33 

Per "eliminare" prodotti da un listino già esistente, al momento è necessario renderli non disponibili nel listino, giusto?

Ovviamente questa modifica avrà impatto su tutti gli ordini futuri che verranno creati a partire da quel listino e non su quelli passati che sono già stati precedentemente creati e che riportano  e al loro interno i prodotti successivamente eliminati. 

Per non vedere più un particolare prodotto tra quelli inseribili in un listino, occorre renderlo Disponibile = NO all'interno dell'Anagrafica Prodotti --> forse converrebbe rinominare quest'ultimo campo con un'altra definizione più "strong" (es. ATTIVO)

**Comment by Jazzo** [comment]
Corretto, tra l'altro il campo stesso della tabella "prodotti" si chiama "attivo".
Dobbiamo lasciare invece come unica possibilità nel listino il "Disabilita" per mantenere traccia nello storico. Possiamo pensare a soluzioni migliori ma per ora chiudo questo issue.
