### ISSUE TITLE
Dare un Nome generico all'ordine (# 43)

### ISSUE THREAD

**Issue by claudiogiare** [iGruppi/iGruppi#73]
Riporto da #43 
Potrebbe risultare utile dare un nome generico all'ordine.
es. ORDINE FERMENTO NATURALE
Potrebbe essere una funzione facoltativa.

Attualmente viene fuori una etichetta "Ordine del gg/mm/aaaa" e l'elenco di tutti i produttori coinvolti. Se sono tanti, è di difficile lettura.
![schermata 07-2457220 alle 23 52 13](https://cloud.githubusercontent.com/assets/7717889/8736046/b4f2702e-2c15-11e5-8a44-df60e3528124.png)

**Comment by Jazzo** [comment]
![schermata 2015-08-23 alle 01 05 16](https://cloud.githubusercontent.com/assets/1465434/9426223/25723660-4933-11e5-9661-accfc33c4009.png)

Cliccando sul pulsante "Multi Produttore" si apre l'elenco dei produttori:

![schermata 2015-08-23 alle 01 05 29](https://cloud.githubusercontent.com/assets/1465434/9426227/359bd7f8-4933-11e5-836e-6aa8d4166501.png)

**Comment by claudiogiare** [comment]
la descrizione dell'ordine viene fuori correttamente nella sezione Gestione Ordini, ma non è visibile nell'Elenco Ordini della sezione "Ordini" (per l'utente "semplice" che deve ordinare).
Penso sia un'informazione utile anche per questa area.
