### ISSUE TITLE
ERRORE CALCOLO QTA' REALE per PRODOTTI a CONFEZIONE (ex #43)

### ISSUE THREAD

**Issue by claudiogiare** [iGruppi/iGruppi#75]
Riporto da #43 
Non effettua il calcolo della qtà reale e conseguentemente dell'importo (prz*qtà) per i prodotti gestiti A CONFEZIONE (in particolare i prodotti creati ultimamente)
![schermata 07-2457221 alle 00 43 47](https://cloud.githubusercontent.com/assets/7717889/8736862/9452fa30-2c1c-11e5-9c02-0ab3eb1a27c7.png)

Probabilmente @marcenuc (mitico!) ha già trovato la soluzione al bug:
https://github.com/iGruppi/iGruppi/issues/43#issuecomment-127664460

Confermo che il campo moltiplicatore degli ultimi prodotti creati è a 0, perchè è rimasto così dal default.
![schermata 08-2457253 alle 22 27 15](https://cloud.githubusercontent.com/assets/7717889/9342302/3e464a68-45fb-11e5-829a-f49eb27bec13.png)

**Comment by Jazzo** [comment]
Ho sistemato anche la situazione su beta2 dove, oltre ad impostare il valore di default nella tabella, ho anche aggiornato tutti i prodotti col moltiplicatore a zero con questa query:
UPDATE `prodotti` SET moltiplicatore=1 WHERE moltiplicatore=0
