### ISSUE TITLE
Agevolazioni filtro nell'Area "Ordini" - Ricerca "Google-Like"

### ISSUE THREAD

**Issue by claudiogiare** [iGruppi/iGruppi#79]
Proviamo a raccogliere qualche idea per rendere più agevole la consultazione della lista dei prodotti disponibili da parte degli utenti "base" all'interno dell'Area "ORDINI", e conseguentemente la funzionalità di ordine (che sarà sicuramente quella più sfruttata in termini di operatività da parte degli utenti) .

Una di queste potrebbe essere un Filtro di Ricerca "Google-Like" che permette di digitare dei caratteri di ricerca e vedersi automaticamente ed in tempo reale la lista dei prodotti filtrata per la stringa indicata nel campo di ricerca.
La ricerca potrebbe essere fatta sul campo descrizione del prodotto, ma eventualmente anche su altri campi (es. Note, Codice, ecc.) dell'anagrafica prodotto.

Una volta entrato nell'ordine,  questa funzionalità potrebbe essere utile per dare una consultazione più agevole e veloce della lista dei prodotti, che in molti casi potrebbe essere anche lunga (es. Saponaria, Ravinala).

**Comment by Jazzo** [comment]
2.1 Claudio, troppa carne al fuoco. Dobbiamo stringere invece di allargarci ;-)

**Comment by Jazzo** [comment]
Per ora funzionante solo sul campo "descrizione prodotto":

![schermata 2015-09-10 alle 21 22 22](https://cloud.githubusercontent.com/assets/1465434/9798721/22429b2c-5803-11e5-92a2-85116e1a0b3f.png)
