### ISSUE TITLE
Errore accesso Gestione Cassa

### ISSUE THREAD

**Issue by claudiogiare** [iGruppi/iGruppi#82]
Quando un utente base (non contabile o amministratore) clicca sulla voce "Gestione cassa" viene fuori un messaggio di errore
![schermata 09-2457277 alle 01 12 21](https://cloud.githubusercontent.com/assets/7717889/9803329/9cac4138-5821-11e5-8d4c-0b974dff14f8.png)
Sarebbe opportuno che il messaggio fosse meno tecnico (non è un errore) o la voce di menu fosse direttamente disabilitata per l'utente non autorizzato.

**Comment by Jazzo** [comment]
Ora chi non è autorizzato all'accesso non vede la voce di menù:

![schermata 2015-09-11 alle 16 44 33](https://cloud.githubusercontent.com/assets/1465434/9817719/f1937ce2-58a4-11e5-80ba-6255955ec0f1.png)
