### ISSUE TITLE
Foreign key incompleta in ordini_user_prodotti.

### ISSUE THREAD

**Issue by marcenuc** [iGruppi/iGruppi#83]
Il vincolo di FOREIGN KEY da `ordini_user_prodotti` a `ordini_prodotti`, non è completo perché non include la colonna `idordine`, necessaria per identificare correttamente la riga di `ordini_prodotti`. Sul mio database ho risolto coi seguenti comandi:

```sql
    ALTER TABLE `ordini_user_prodotti`
      DROP foreign key `fk_ordini_user_prodotti_ordini_prodotti1`;
    ALTER TABLE `ordini_user_prodotti`
      ADD CONSTRAINT `fk_ordini_user_prodotti_ordini_prodotti1`
      FOREIGN KEY (`idordine`, `idlistino`, `idprodotto`)
      REFERENCES `ordini_prodotti` (`idordine`, `idlistino`, `idprodotto`)
      ON DELETE NO ACTION ON UPDATE NO ACTION
```

Non ho fatto una pull request perché non so come gestisci gli aggiornamenti dello schema del database. Questa sarebbe una cosa importante da scrivere nella documentazione. Io adesso mi guardo uno ad uno i commit e cerco di replicare a manina ogni modifica... c'è un modo migliore?

A me basterebbe avere una cartella con dei file SQL che applicano le modifiche e alla fine aggiornano la versione dello schema in un'apposita tabella. Così basta vedere che versione è in produzione e applicare in sequenza tutte le versioni successive. Purtroppo in MySQL le modifiche allo schema non sono transazionali, quindi bisogna fare un backup prima di ogni aggiornamento, ma sarebbe comunque una grossa semplificazione. Che ne dite?

**Comment by Jazzo** [comment]
@marcenuc per le versioni precedenti alla 2.0 esistono i file che dici tu in [documentation/updates](https://github.com/iGruppi/iGruppi/tree/master/documentation/updates) per passare da uno schema all'altro. Nella versione 2.0 non ho ancora rilasciato alcun aggiornamento in questo senso perchè ancora non è un branch in produzione. Appena verrà rilasciata la versione 2.0 andremo avanti in questo modo. 

Per il passaggio dei tuoi dati però tu puoi verificare il log commits del file [igruppi_dump_2.sql](https://github.com/iGruppi/iGruppi/commits/master/documentation/database/igruppi_dump_2.sql)

Quanto alla FK qual è il problema che hai riscontrato?

**Comment by marcenuc** [comment]
@Jazzo, è proprio quello che ho fatto: ho verificato i commit sul file igruppi_dump_2.sql. Il problema è che non è banale intuire i comandi da lanciare per fare le modifiche, allora ti chiedevo come stai facendo tu ad applicare le modifiche. Se stai modificando direttamente il database sul server di test, ti basterebbe salvare in un file i comandi SQL che esegui man mano, e includere il file nel commit.

Il problema degli script in [documentation/updates](https://github.com/iGruppi/iGruppi/tree/master/documentation/updates), è che non servono a chi sta testando iGruppi 2.0 sul proprio GAS.

L'ideale sarebbe che ogni commit che contiene modifiche al database, contenesse anche una versione del database e la salvasse in un'apposita tabella. In questo modo sarebbe semplice sapere che database si sta usando. Ma capisco che potrebbe diventare troppo oneroso da mantenere.

Quanto alla FK, il problema è che non punta ad una chiave **univoca** della tabella `ordini_prodotti`, perché manca la colonna `idordine`, quindi di fatto non serve a garantire che la riga necessaria in `ordini_prodotti` esista. In pratica basta che quel prodotto di quel listino sia presente in un qualsiasi altro ordine, per poterlo inserire in `ordini_user_prodotti`, anche se quel prodotto non esiste in quell'ordine.

In altre parole: visto che l'unica chiave **univoca** di `ordini_prodotti` è `(idordine,idlistino,idprodotto)`, tutte le FK che puntano a questa tabella possono puntare solo a questa chiave. Altrimenti non servono a niente perché non garantiscono che il record voluto esista.

**Comment by Jazzo** [comment]
>
> @Jazzo <https://github.com/Jazzo>, è proprio quello che ho fatto: ho
> verificato i commit sul file igruppi_dump_2.sql. Il problema è che non è
> banale intuire i comandi da lanciare per fare le modifiche, allora ti
> chiedevo come stai facendo tu ad applicare le modifiche. Se stai
> modificando direttamente il database sul server di test, ti basterebbe
> salvare in un file i comandi SQL che esegui man mano, e includere il file
> nel commit.
>
Io guardo da quel file che campo è stato aggiunto e poi lo aggiungo via
phpMyAdmin.

Il problema degli script in documentation/updates
> <https://github.com/iGruppi/iGruppi/tree/master/documentation/updates>, è
> che non servono a chi sta testando iGruppi 2.0 sul proprio GAS.
>
Infatti, era a titolo di esempio per farti capire come avevo lavorato per
le precedenti versioni.
Per la 2.0, ribadisco, non è in produzione e quando lo sarà ci muoveremo in
questo modo.

L'ideale sarebbe che ogni commit che contiene modifiche al database,
> contenesse anche una versione del database e la salvasse in un'apposita
> tabella. In questo modo sarebbe semplice sapere che database si sta usando.
> Ma capisco che potrebbe diventare troppo oneroso da mantenere.
>
Questa è una soluzione ma ne esistono anche altre, ad esempio implementare
degli script per l'aggiornamento automatico come fanno tutti gli altri.
Siccome però io sto ora gestendo il passaggio in produzione della 2.0 e non
ho tempo di occuparmi di questa cosa, ci pensi tu?


> Quanto alla FK, il problema è che non punta ad una chiave *univoca* della
> tabella ordini_prodotti, perché manca la colonna idordine, quindi di
> fatto non serve a garantire che la riga necessaria in ordini_prodotti
> esista. In pratica basta che quel prodotto di quel listino sia presente in
> un qualsiasi altro ordine, per poterlo inserire in ordini_user_prodotti,
> anche se quel prodotto non esiste in quell'ordine.
>
> In altre parole: visto che l'unica chiave *univoca* di ordini_prodotti è
> (idordine,idlistino,idprodotto), tutte le FK che puntano a questa tabella
> possono puntare solo a questa chiave. Altrimenti non servono a niente
> perché non garantiscono che il record voluto esista.
>
Il problema della FK l'ho capito bene.
Siccome però stiamo rilasciando la versione 2.0 ti chiedevo se hai
riscontrato problemi. Da un punto di vista logico il tuo ragionamento non
fa una piega ma come ben sai da codice posso tranquillamente "superare"
questo inconveniente se le query son scritte avendo ben presente quale sia
la reale FK. Ecco perchè ti chiedevo se avevi riscontrato problemi sul
codice, perchè al momento sarebbe urgente sistemarlo. Viceversa, lo
sistemeremo con calma e chiudo questo issue che per tutto il resto riguarda
solo la tua situazione (vedi sopra). Poi ovviamente continuiamo via email.

**Comment by marcenuc** [comment]
> Questa è una soluzione ma ne esistono anche altre, ad esempio implementare degli script per l'aggiornamento automatico come fanno tutti gli altri. Siccome però io sto ora gestendo il passaggio in produzione della 2.0 e non ho tempo di occuparmi di questa cosa, ci pensi tu?

Certo, posso farlo io. Ti chiedo solo se hai una preferenza su cosa usare, perché in PHP non conosco software di questo tipo. Il mio preferito è http://flywaydb.org/, ma non ho mai trovato niente di simile in PHP.

> Il problema della FK l'ho capito bene. Siccome però stiamo rilasciando la versione 2.0 ti chiedevo se hai riscontrato problemi.

Scusa, non avevo capito la domanda... Non so se ci sono problemi sul codice. Infatti questa segnalazione è per correggere il database, non il codice. Il problema l'ho notato cercando di cancellare un ordine dal database: non potevo rimuovere i record in `ordini_prodotti` perché quei prodotti erano stati ordinati in un precedente ordine. Correggendo la FK, ho potuto fare pulizia.

Quindi cambio la domanda: posso correggere questo tipo di errori con una PR che aggiorna igruppi_dump_2.sql o devo aspettare la messa in produzione della 2.0?

**Comment by Jazzo** [comment]
>
> Certo, posso farlo io. Ti chiedo solo se hai una preferenza su cosa usare,
> perché in PHP non conosco software di questo tipo. Il mio preferito è
> http://flywaydb.org/, ma non ho mai trovato niente di simile in PHP.
>
Io non ne conosco perchè solitamente lo faccio a mano (un po' rudimentale,
lo so).
Però tu fai come preferisci, tools come questi dovrebbero alla fine
generare comunque un file SQL che posizionerei nella directory
documentation/updates


Quindi cambio la domanda: posso correggere questo tipo di errori con una PR
> che aggiorna igruppi_dump_2.sql o devo aspettare la messa in produzione
> della 2.0?
>
Certo che puoi!

**Comment by Jazzo** [comment]
![schermata 2015-09-17 alle 12 22 03](https://cloud.githubusercontent.com/assets/1465434/9931092/d147dfa8-5d38-11e5-81a9-6f4f2e1f5a77.png)

**Comment by marcenuc** [comment]
@Jazzo, ottimo... non l'avevo fatto subito perché mi era venuto il dubbio di come aggiornare il file iGruppi_2-0.mwb... se ho capito bene, tu fai la correzione con il Workbench di MySQL e poi esporti il dump SQL dello schema del database. Giusto?

**Comment by Jazzo** [comment]
@marcenuc proprio così! 

Ho creato una pagina di documentazione:
[01. Struttura Database](https://github.com/iGruppi/iGruppi/wiki/01.-Struttura-database)

Ovviamente la procedura è migliorabile ma almeno per ora abbiamo una linea guida da seguire ;-)
