### ISSUE TITLE
filtro ordini per Produttore

### ISSUE THREAD

**Issue by monicapgiare** [iGruppi/iGruppi#87]
Nel menù Ordini, si vedono disponibili il filtro per stato e il filtro per produttore.
Il primo funziona, scegliendo il secondo non appare niente.
E' sempre stato così ed è una funzione che sarà sviluppata in seguito, oppure è un errore?
NON ne abbiamo bisogno subito, solo per saperlo.

![image](https://cloud.githubusercontent.com/assets/11527743/9982101/c661a0e8-5fd0-11e5-9ec4-4cf254fa830e.png)

**Comment by Jazzo** [comment]
Roba vecchia, eliminato.
In futuro poi magari metteremo il filtro per Categoria di prodotti ma dobbiamo ragiornarci un attimo.
