### ISSUE TITLE
Specificare charset connessione al database

### ISSUE THREAD

**Issue by marcenuc** [iGruppi/iGruppi#88]
Ho avuto diversi problemi di codifica di caratteri con lettere accentate, apici e altri caratteri non ASCII.

Esempio: se carico l'anagrafica prodotti importando un CSV (codificato in UTF-8) con phpMyAdmin (configurato per connettersi al DB con charset=utf8_general_ci), in phpMyAdmin e da linea di comando visualizza correttamente tutte le descrizioni, ma in iGruppi tutti i caratteri non ASCII sono visualizzati con un punto interrogativo. Inoltre le pagine con una tabella Handsontable sono vuote perché la conversione in JSON fallisce.

L'esempio funziona anche al contrario: se carico una descrizione con lettere accentate da iGruppi, non la visualizzo correttamente da altri programmi.

**Ho risolto il problema**, sul mio server, forzando iGruppi ad usare UTF-8 per connettersi al DB. Non sapendo come farlo da configurazione, ho modificato [la riga 15 di `library/MyFw/DB.php`](https://github.com/Jazzo/MyFw/blob/36cb962b5ed4aeb9b44c71728e32eaaac27dc2dc/DB.php#L15) da:

```php
  $dsn = 'mysql:host='.$dbParams->host.';dbname='.$dbParams->dbname;
```
a:

```php
  $dsn = 'mysql:host='.$dbParams->host.';dbname='.$dbParams->dbname.';charset=utf8';
```

Ci sono soluzioni più pulite o serve una PR per MyFw?

**Comment by Jazzo** [comment]
Direi che va bene così e grazie per l'ottima fix.
Procedi pure con la PR su MyFw.
