### ISSUE TITLE
Gestione Listini - Modifica prezzi abilitato a tutti gli utenti

### ISSUE THREAD

**Issue by claudiogiare** [iGruppi/iGruppi#91]
Al momento un qualsiasi utente di un gruppo può modificare i prezzi di un listino.
Dovrebbe poterlo fare solo il referente per quel produttore a cui il listino si riferisce.

**Comment by Jazzo** [comment]
Ho provato un po' ma non ho trovato come.
Mi dai un utente su beta2 che può farlo?
