### ISSUE TITLE
mail relativa alla prossima chiusura di un ordine per i ritardatari

### ISSUE THREAD

**Issue by StefanoMenozzi** [iGruppi/iGruppi#92]
In un ordine condiviso con il gas Le Giare (la Madè), non mi pare arrivino le mail relative alla prossima chiusura dell'ordine per gli ultimi ritardatari. 
E' stato eliminato come messaggio?
Oppure per gli ordini condivisi non arriva?
Oppure me lo sono perso io?

**Comment by Jazzo** [comment]
Purtroppo le notifiche tutte sono ancora disabilitate su Live.
