### ISSUE TITLE
Ordine "vuoto" non archiviabile

### ISSUE THREAD

**Issue by monicapgiare** [iGruppi/iGruppi#96]
Un ordine condiviso da altro gruppo, non reso visibile, quindi senza prodotti ordinati, avanza di stato normalmente, ma non appare il pulsante "archivia". Rimane per sempre "consegnato", apparendo sempre tra gli ordini da chiudere per il contabile?

![image](https://cloud.githubusercontent.com/assets/11527743/11171255/d27f2b1a-8beb-11e5-9727-95c5205df23e.png)

![image](https://cloud.githubusercontent.com/assets/11527743/11171257/d7e80afe-8beb-11e5-85dd-275d871d085d.png)

**Comment by Jazzo** [comment]
E' corretto.
Le date, quindi l'avanzamento dell'ordine, è in capo alla tabella ordini
(gestite da Supervisore). Idem l'archiviazione che però è in capo al
Contabile. L'ordine verrà Archiviato per tutti dal contabile e il sistema
ripartirà le somme sui singoli utenti di tutti i gruppi.

**Comment by Jazzo** [comment]
Fixed.
Lo stato dell'ordine viene portato avanti dal Supervisore fino allo stato di CONSEGNATO. Poi il Contabile può procedere all'archiviazione. Ogni Contabile archivia l'ordine per il proprio gruppo.
